### ISSUE TITLE
"Update API documentation" CI workflow disabled from inactivity

### ISSUE THREAD

**Issue by dylanahsmith** [v8/api#10]
If you go https://github.com/v8/api/actions/workflows/update-api-docs.yml then you will see the message

>  This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days.

with the last run of that action being 7 months ago.

**Comment by dylanahsmith** [comment]
@LeszekSwirski are you able to just re-enable the scheduled workflow for now?

**Comment by LeszekSwirski** [comment]
Thanks for catching this, manually enabled.
