### ISSUE TITLE
The graphs aren't shown on the V8 API Reference Guide pages

### ISSUE THREAD

**Issue by agrexgh** [v8/api#7]
I'd like to see the graphs like `Inheritance graph` and `Collaboration graph`,
but I can't see them.

For example, like below.
https://v8docs.nodesource.com/node-8.16/db/d85/classv8_1_1_object.html

Other pages also don't show the graphs.

**Comment by LeszekSwirski** [comment]
The page you linked is an external one, that we don't have control over. I see the graphs on the official https://v8.github.io/api/head/classv8_1_1Object.html, does that work for you?

**Comment by agrexgh** [comment]
@LeszekSwirski 
Thank you for introducing official site.
I misunderstood the one I linked is official.

I need a little more help of you.
I'd like to reference of v8 version **6.2.414**.
Is your link the one of that?
If not, where can I found it?

**Comment by LeszekSwirski** [comment]
You want https://v8.github.io/api/v6.2/classv8_1_1Object.html

**Comment by agrexgh** [comment]
@LeszekSwirski 
It is just what i'd like!
Thank you!
